import { Pipe, PipeTransform } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

/**
 * Custom Pipe — transforms plain code text into syntax-highlighted HTML.
 *
 * Strategy: tokenize first (extract all matches in priority order), then
 * rebuild the string with spans. This prevents cascading where a later
 * rule matches inside HTML attributes generated by an earlier rule.
 */
@Pipe({
  name: 'syntaxHighlight',
  standalone: true,
  pure: true
})
export class SyntaxHighlightPipe implements PipeTransform {

  constructor(private sanitizer: DomSanitizer) {}

  private readonly rules: Array<{ pattern: RegExp; className: string }> = [
    // Comments first (highest priority)
    { pattern: /\/\/.*/g, className: 'hl-comment' },
    { pattern: /\/\*[\s\S]*?\*\//g, className: 'hl-comment' },
    // Strings
    { pattern: /(["'`])(?:(?=(\\?))\2.)*?\1/g, className: 'hl-string' },
    // Annotations
    { pattern: /@\w+/g, className: 'hl-annotation' },
    // Java/Kotlin keywords
    { pattern: /\b(public|private|protected|class|interface|abstract|static|final|void|return|new|if|else|for|while|do|switch|case|break|continue|try|catch|finally|throw|throws|import|package|extends|implements|super|this|null|true|false|var|val|fun|suspend|sealed|data|object|companion|override|open|enum|record|sealed|permits|instanceof|yield|when|is|as|in|by)\b/g, className: 'hl-keyword' },
    // Types
    { pattern: /\b(String|Int|Long|Double|Float|Boolean|Char|Byte|Short|Unit|Nothing|Any|List|Map|Set|Optional|Stream|CompletableFuture|Object|Array|Duration|Instant|Route|Delivery|Driver|BigDecimal|Integer|Void)\b/g, className: 'hl-type' },
    // Numbers
    { pattern: /\b\d+\.?\d*[fFdDlL]?\b/g, className: 'hl-number' },
  ];

  transform(code: string): SafeHtml {
    if (!code) return '';

    const escaped = this.escapeHtml(code);

    // Track which character positions are already claimed
    const claimed = new Uint8Array(escaped.length);
    const tokens: Array<{ start: number; end: number; className: string; text: string }> = [];

    // Find all matches in priority order; skip overlapping regions
    for (const rule of this.rules) {
      const regex = new RegExp(rule.pattern.source, rule.pattern.flags);
      let match: RegExpExecArray | null;
      while ((match = regex.exec(escaped)) !== null) {
        const start = match.index;
        const end = start + match[0].length;

        // Check if any character in this range is already claimed
        let overlaps = false;
        for (let i = start; i < end; i++) {
          if (claimed[i]) { overlaps = true; break; }
        }
        if (overlaps) continue;

        // Claim this range
        for (let i = start; i < end; i++) { claimed[i] = 1; }
        tokens.push({ start, end, className: rule.className, text: match[0] });
      }
    }

    // Sort tokens by position (earlier first)
    tokens.sort((a, b) => a.start - b.start);

    // Rebuild string with spans
    let result = '';
    let pos = 0;
    for (const token of tokens) {
      // Add unclaimed text before this token
      if (token.start > pos) {
        result += escaped.slice(pos, token.start);
      }
      result += `<span class="${token.className}">${token.text}</span>`;
      pos = token.end;
    }
    // Add remaining text after last token
    result += escaped.slice(pos);

    return this.sanitizer.bypassSecurityTrustHtml(result);
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
  }
}
